spring:
  application:
    name: Expense-Tracker-Backend-Java

  datasource:
    # url: jdbc:postgresql://<HOST>:<PORT>/<DB_NAME>
    # username: <DB_USERNAME>
    # password: <DB_PASSWORD>
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
#    default-schema: public
#    drop-first: false


server: